### ISSUE TITLE
One tool to rule them all

### ISSUE THREAD

**Issue by gabrielctn** [phnmnl/container-isa-extractor#1]
Hi @pkrog thanks for this tool !
Just wondering if is it planned to have this tool available in PhenoMeNal as for example "isa2mzfiles" or "isa-extractor" that would combine all the isa2[mzml,netcdf,mzxml,mzdata,nmrml] you developed ? It would for instance detect the files inside the study and use the appropriate isa2* to output the galaxy collection.
Thanks again for your work!

**Comment by pkrog** [comment]
Hi Gabriel,
Maybe I'm wrong, but I don't think you can define a dynamic output in Galaxy. At least, I don't know how to do it. Moreover if you want to use a tool inside a Galaxy workflow, it's better to have the outputs well defined, or you take the risk to pass a file or a collection that is not handled by the next tool.
However I think that the tool "Get data files collection" output all data files mixed together inside a single collection, maybe that could suit your needs. Of course this means the collection is not "typed".

**Comment by gabrielctn** [comment]
Hi,
Oh sorry it was ambiguous, I didn't mean a detection _before_ the tool (even though that would be terribly good), but a tool that would read the study, detect the type of files inside (choosing only the accepted extensions), and output the corresponding dataset.
Would that make the output of the tool not well defined you think?
The tool "Get data files collection" is filtering on factors... and outputing a json if I understand correctly, not the actual files, is it?

**Comment by pkrog** [comment]
"Get data files collection" outputs a collection, this is "Get data files list" that outputs you a list of the files.

When you define the output in the XML tool file, you must set the type of the output. This is true also for collections. If you output unknown files into a collection, you cannot specify the format of the files, and your collection is set to contain files of unknown type. You then cannot plug it to the input of a tool accepting only collection of mzML files for instance.

**Comment by gabrielctn** [comment]
Ok so then their tool description needs to be updated because it is exactly the same for both tools...

Alright I understand better now, thank you for the explanations.

**Comment by gabrielctn** [comment]
I guess we can close it now? Re-open if necessary
