### ISSUE TITLE
Case sensitive datatype extension not recognized

### ISSUE THREAD

**Issue by gabrielctn** [phnmnl/container-isa-extractor#3]
Hi @pkrog ,
I have a datatype extension issue when trying to read the collection output of isa2mzml.
The format of the files inside the collection are `format: mzML` and when I try using the collection as input it is not recognized.
In my tool wrapper for the input I use:  
```xml
<param name="ipo4xcmsSet_input" type="data" format="mzxml,mzml,mzdata,netcdf" multiple="True" />
```  
and the error in the log is:  
```
galaxy.model WARNING 2018-05-25 08:27:37,786 Datatype class not found for extension 'mzML'`
```
Having these both lines in `datatypes_conf.xml` does not help:
```xml
<datatype extension="mzml" type="galaxy.datatypes.proteomics:MzML" mimetype="application/xml" display_in_upload="true"/>
<datatype extension="mzML" type="galaxy.datatypes.proteomics:MzML" mimetype="application/xml" display_in_upload="true"/>
```
Adding mzML as a format in the wrapper also didn't solve the problem:
```xml
<param name="ipo4xcmsSet_input" type="data" format="mzxml,mzml,mzML,mzdata,netcdf" multiple="True" />
```

If I re-upload the same files as a new collection in galaxy with the format `mzml`, then the new collection is recognized. So I think there is maybe missing somewhere the extension "mzML", perhaps in the `class MzML(ProteomicsXml):` definition ?
This issue might also apply to mzXML, mzData and netCDF.

**Comment by sneumann** [comment]
Same here with MTBLS36, and I can't get the mzML collection I need for xcms. 
Anything where I can aid debugging ? Yours, Steffen

**Comment by pkrog** [comment]
Could you please point to the code of your tool that takes mzML collection as input, so I can install it and test within regular Galaxy?

**Comment by sneumann** [comment]
I used a recent PhenoMeNal installation, data of MTBLS36 was downloaded with 
`Metabolights downloader Import public and private MetaboLights studies (Galaxy Version 3.1.0) / mtbls-dwnld&version=3.1.0` 
and then I wanted to extract with `ISA to mzML Extract mzML files from an ISA dataset and output a collection of mzML dataset. (Galaxy Version 1.1.0) / tool_id=isa2mzml&version=1.1.0`

**Comment by pkrog** [comment]
Sorry @sneumann , I meant the tool used by @gabrielctn after isa2mzml: which one is it?

So, Steffen, you're issue is you get an empty collection, right?

**Comment by sneumann** [comment]
It hangs forever in yellow, even after the container has excited

---
I blame Android for the brevity and typos

**Comment by pkrog** [comment]
Ok, so this is another problem. Could you open another issue @sneumann, please?

**Comment by gabrielctn** [comment]
@pkrog The tool after isa2mzml is _ipo for xcmsSet_ but I just tested on my laptop it's not even on github yet, but the code I use is the first line in my first message, it's the (almost) the only thing that changed from the current version. I just want to read the collection, but the big case in mzML is not recognized.

**Comment by pkrog** [comment]
But it should not stay in yellow. It should output an empty collection.
I'll run isa2mzml on MTBLS36 on my computer.

**Comment by pkrog** [comment]
It should be solved with latest commit in develop.
See also phnmnl/container-galaxy-k8s-runtime#194.
